### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by moseisleydk** [calmjm/tojota#13]
Hi,

Great work - but Im getting:

(tojota) ╭─bnp@sparrow ~/tojota ‹master*›
╰─$ python tojota.py
2020-11-08 18:31:32,757:__main__:INFO: Logging in...
2020-11-08 18:31:33,496:__main__:INFO: Fetching trips...
Traceback (most recent call last):
  File "tojota.py", line 419, in <module>
    sys.exit(main())
  File "tojota.py", line 342, in main
    latest_address = trips['recentTrips'][0]['endAddress']
IndexError: list index out of range
(tojota) ╭─bnp@sparrow ~/tojota ‹master*›
╰─$

**Comment by calmjm** [comment]
Code didn't expect that there are no trips. Exception fixed in https://github.com/calmjm/tojota/pull/14 .
