### ISSUE TITLE
Get odometer info... error

### ISSUE THREAD

**Issue by moseisleydk** [calmjm/tojota#21]
╰─# python ./tojota.py
2021-01-31 10:46:51,682:__main__:INFO: Fetching trips...
2021-01-31 10:46:52,038:__main__:INFO: Failed to use cached token, doing fresh login...
2021-01-31 10:46:52,038:__main__:INFO: Logging in...
2021-01-31 10:46:52,812:__main__:INFO: Fetching trips...
2021-01-31 10:46:53,384:__main__:INFO: Get parking info...
Didn't get parking information!
2021-01-31 10:46:53,719:__main__:INFO: Get odometer info...
Traceback (most recent call last):
  File "./tojota.py", line 457, in <module>
    sys.exit(main())
  File "./tojota.py", line 399, in main
    odometer, odometer_unit, fuel_percent, fresh = myt.get_odometer_fuel()
  File "./tojota.py", line 232, in get_odometer_fuel
    raise ValueError('Failed to get data {} {} {}'.format(r.text, r.status_code, r.headers))
ValueError: Failed to get data  204 {'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Server': 'Jetty(9.3.25.v20180904)', 'Request-Context': 'appId=**********', 'ID': '************, 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'DENY', 'X-Powered-By': 'ASP.NET', 'Set-Cookie': 'ARRAffinity=***********;Path=/;HttpOnly;Secure;Domain=myt-agg.toyota-europe.com, ARRAffinitySameSite=cdbb42914fa53f4972f5e7c6469f3e4ef2f3e5cb1017cfc16cde43debbb77243;Path=/;HttpOnly;SameSite=None;Secure;Domain=myt-agg.toyota-europe.com, visid_incap_2173333=wRKaOwsKSnqUun+chVidjI18FmAAAAAAQUIPAAAAAACb1TdhBldQBtQm85tvQROx; expires=Sun, 30 Jan 2022 11:49:57 GMT; HttpOnly; path=/; Domain=.toyota-europe.com, incap_ses_1104_2173333=MO8WZtWUPFz6WoZybDJSD418FmAAAAAADuiVMDYS4RhwavKjI7iCqg==; path=/; Domain=.toyota-europe.com, ___utmvmoZBuyvPZZ=EKlDNdcLjba; path=/; Max-Age=900, ___utmvaoZBuyvPZZ=ARX\x01PDSQ; path=/; Max-Age=900, ___utmvboZBuyvPZZ=CZZ\r\n    XKkOUalY: XtT; path=/; Max-Age=900', 'Date': 'Sun, 31 Jan 2021 09:46:53 GMT', 'X-CDN': 'Incapsula', 'X-Iinfo': '2-************ PNNy RT(1612086413591 21) q(0 0 0 0) r(2 2) U11'}
(tojota) ╭─root@sparrow ~/tojota ‹master*›
╰─#

**Comment by moseisleydk** [comment]
Thanks for fixing #16

**Comment by moseisleydk** [comment]
ok, MyT app stalls at 65% now .... will test later

**Comment by moseisleydk** [comment]
Ok, MyT works now:

![IMG_8454](https://user-images.githubusercontent.com/15978685/106380584-882edb00-63b3-11eb-9871-4ff772965f17.PNG)

**Comment by calmjm** [comment]
I suggest you check your VIN from the config. It seems than when you have invalid VIN there all the data is returned as HTTP 204 instead of expected HTTP 403. Maybe you have copy-paste error there?

**Comment by moseisleydk** [comment]
Hi,

You were correct, my bad :-(

Current status:

╰─# python ./tojota.py
2021-01-31 11:10:00,142:__main__:INFO: Fetching trips...
2021-01-31 11:10:01,543:__main__:INFO: Failed to use cached token, doing fresh login...
2021-01-31 11:10:01,544:__main__:INFO: Logging in...
2021-01-31 11:10:02,536:__main__:INFO: Fetching trips...
Traceback (most recent call last):
  File "./tojota.py", line 371, in main
    trips, fresh = myt.get_trips()
  File "./tojota.py", line 161, in get_trips
    self._write_file(trips_file, r.text)
  File "./tojota.py", line 109, in _write_file
    f.write(contents)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe6' in position 170: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tojota.py", line 457, in <module>
    sys.exit(main())
  File "./tojota.py", line 375, in main
    trips, fresh = myt.get_trips()
  File "./tojota.py", line 161, in get_trips
    self._write_file(trips_file, r.text)
  File "./tojota.py", line 109, in _write_file
    f.write(contents)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe6' in position 170: ordinal not in range(128)
(tojota) ╭─root@sparrow ~/tojota ‹master*›
╰─#

**Comment by moseisleydk** [comment]
Argh - think I have solved that earlier with something in the top line ...

**Comment by moseisleydk** [comment]
no, adding:

# encoding=utf8

Did not solve it

**Comment by calmjm** [comment]
Which python version are you using?

**Comment by moseisleydk** [comment]
(tojota) ╭─root@sparrow ~/tojota ‹master*›
╰─# python --version                                                                                                                              1 ↵
Python 3.6.9
(tojota) ╭─root@sparrow ~/tojota ‹master*›
╰─#

**Comment by calmjm** [comment]
Hmm. Python 3.x should not have that problem at all. Adding # -*- coding: utf-8 -*- was the fix for python 2.

**Comment by moseisleydk** [comment]
Anything I can do to assist? I am a total python noob

**Comment by calmjm** [comment]
Can you provide that problematic trips file as an attachment here? Get trips.json with curl like

`curl -H 'X-TME-TOKEN: [your_secret_token]'  -o trips.json https://cpb2cs.toyota-europe.com/api/user/[your_uuid]/cms/trips/v2/history/vin/[your_vin]/1` 

where [your_secret_token] and [your_uuid] can be found from cache/user_data.json after you have run tojota.py recently and [vin] is your car VIN. 

If you don't feel comfortable posting your driving data here send it via email to me.

**Comment by moseisleydk** [comment]
No problem, heres there file. Im from Denmark, så some æøå


[trips.zip](https://github.com/calmjm/tojota/files/5900092/trips.zip)

**Comment by calmjm** [comment]
I'm in Finland so we have some öäöä here too and those are not a problem. File content seems to be fine for me, need to do some more python testing with it.

**Comment by moseisleydk** [comment]
Sure, do leave a message for me if my tests are needed. Appreciate the effort!!

BR,

Normann
