### ISSUE TITLE
statistics.py

### ISSUE THREAD

**Issue by backfisch88** [calmjm/tojota#33]
worked great since friday :/

no I get this:

````
2021-05-31 19:03:50,184:__main__:INFO: Failed to use cached token, doing fresh login...
2021-05-31 19:03:50,184:tojota:INFO: Logging in...
Traceback (most recent call last):
  File "/home/pi/myt/statistics.py", line 159, in main
    data, fresh = myt.get_driving_statistics(from_date, interval)
  File "/home/pi/myt/tojota.py", line 304, in get_driving_statistics
    raise ValueError('Failed to get data {} {} {}'.format(r.text, r.status_code, r.headers))
ValueError: Failed to get data {"timestamp":1622480630165,"status":400,"error":"Bad Request","message":"Missing request header 'X-TME-BRAND' for method parameter of type String","errorCode":"CMA400"} 400 {'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Content-Type': 'application/json', 'Expires': '0', 'ID': '4680a306-13b5-45af-b3b0-15aacaee71a0', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'DENY', 'Date': 'Mon, 31 May 2021 17:03:50 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive, Transfer-Encoding', 'Set-Cookie': 'ARRAffinity=46a02d2c2990fcaa816a7ff4d1d4e42a9ca1fb29ab14e5b2ae2c45c295022ac2;Path=/;HttpOnly;Secure;Domain=myt-agg.toyota-europe.com, ARRAffinitySameSite=46a02d2c2990fcaa816a7ff4d1d4e42a9ca1fb29ab14e5b2ae2c45c295022ac2;Path=/;HttpOnly;SameSite=None;Secure;Domain=myt-agg.toyota-europe.com', 'Strict-Transport-Security': 'max-age=86400'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/myt/statistics.py", line 173, in <module>
    sys.exit(main())
  File "/home/pi/myt/statistics.py", line 163, in main
    data, fresh = myt.get_driving_statistics(from_date, interval)
  File "/home/pi/myt/tojota.py", line 304, in get_driving_statistics
    raise ValueError('Failed to get data {} {} {}'.format(r.text, r.status_code, r.headers))
ValueError: Failed to get data {"timestamp":1622480631037,"status":400,"error":"Bad Request","message":"Missing request header 'X-TME-BRAND' for method parameter of type String","errorCode":"CMA400"} 400 {'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Content-Type': 'application/json', 'Expires': '0', 'ID': '789352b4-abfd-4625-95b3-e222185fef9e', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'DENY', 'Content-Length': '168', 'Date': 'Mon, 31 May 2021 17:03:51 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'ARRAffinity=46a02d2c2990fcaa816a7ff4d1d4e42a9ca1fb29ab14e5b2ae2c45c295022ac2;Path=/;HttpOnly;Secure;Domain=myt-agg.toyota-europe.com, ARRAffinitySameSite=46a02d2c2990fcaa816a7ff4d1d4e42a9ca1fb29ab14e5b2ae2c45c295022ac2;Path=/;HttpOnly;SameSite=None;Secure;Domain=myt-agg.toyota-europe.com', 'Strict-Transport-Security': 'max-age=86400'}

**Comment by backfisch88** [comment]
fixed by myself:
in tojota.py line 395 added Brand and locale like this
headers = {'Cookie': f'iPlanetDirectoryPro={token}', 'uuid': uuid, 'vin': vin, 'X-TME-BRAND': 'TOYOTA', 'X-TME-LOCALE': 'fi-fi'}
